# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
      kernelModules = [ ];
      luks.devices."luks-2d691187-0455-4ef5-8d33-dd95d46791ec" = {
        device = "/dev/disk/by-uuid/2d691187-0455-4ef5-8d33-dd95d46791ec";
        bypassWorkqueues = true;
      };
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    { device = "/dev/mapper/luks-2d691187-0455-4ef5-8d33-dd95d46791ec";
      fsType = "ext4";
      options = [ "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4269-F95C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" "nosuid" "noexec" "nodev" ];
    };

  swapDevices = [ ];

  # nixpkgs.hostPlatform set via read-only pkgs in flake.nix
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
