use_nerdfont=true

statusbar_format = "%artists - %title"

[track_format]
left = "%artists - %title"
center = "%album"
right = "%saved %duration"

notify=true
[notification_format]
title = "%title"
body = "%artists"

[theme]
# background = "default"
# # background = "#24283b"
# primary = "#c0caf5"
# secondary = "#1a1b26"
# title = "#e0af68"
# playing = "#7dcfff"
# playing_selected = "#73daca"
# playing_bg = "#1a1b26"
# highlight = "#73daca"
# highlight_bg = "#1a1b26"
# error = "#c0caf5"
# error_bg = "#f7768e"
# statusbar = "#24283b"
# statusbar_progress = "#73daca"
# statusbar_bg = "#7dcfff"
# cmdline_bg = "#24283b"
# search_match = "#bb9af7"

background = "default"
primary = "#cdd6f4" 
secondary = "bac2de" 
title = "#cba6f7"
playing = "#cba6f7" 
playing_selected = "#000000" 
playing_bg = "default"
highlight = "#000000" 
highlight_bg = "#a6e3a1" 
error = "black"
error_bg = "#f38ba8"
statusbar = "#191414"
statusbar_progress = "#cba6f7"
statusbar_bg = "#cba6f7"
cmdline = "#cdd6f4"
cmdline_bg = "#191414"
search_match = "#f38ba8"
