theme = "tokyonight"

[editor]
true-color = true
cursorline = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
color-modes = true

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1