name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Readme generation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure
        run: sudo apt-get update && sudo apt-get install libimage-exiftool-perl
      - name: Build
        run: |
          ./.github/docgen.py
      - name: Commit
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          COMMIT_MSG: |
            [README] Generated readmes.
        run: |
          git config user.email "actions@github"
          git config user.name "Github Actions"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin HEAD:${GITHUB_REF})
